---
# tasks file for apidb-collect cisco

- name: Create custom fact directory
  file:
    path: /tmp/facts
    state: directory
  delegate_to: localhost

- name: Add Cisco Ios facts to a variable 
  cisco.ios.ios_facts:
    gather_subset: all
  register: setupvar

- name: debug
  debug:
    var: setupvar
    verbosity: 3  

- name: Store facts indexed by hostname in /tmp/facts
  copy:
    content: '{{ setupvar }}'
    dest: /tmp/facts/{{ inventory_hostname }}.yaml
    mode: 0600
  delegate_to: localhost
