---
- name: Run Linux collection
  include_tasks: collections/ansible_collections/apidb/ansibledb_opensource/roles/apidb_collect/tasks/linux.yml
  when: ansible_os_family == "RedHat" or ansible_os_family == "Debian"

- name: Run Windows collection
  include_tasks: collections/ansible_collections/apidb/ansibledb_opensource/roles/apidb_collect/tasks/windows.yml
  when: ansible_os_family == "Windows"
