---
- name: Create custom fact directory
  file:
    path: /tmp/facts
    state: directory
  delegate_to: localhost

- name: Create WIndows DIR
  win_file:
    path: C:\Temp\facts
    state: directory

- name: Add facts to a variable
  setup:
    fact_path: C:/TEMP/facts
  register: setupvar

- name: Store facts indexed by hostname in /tmp/facts
  copy:
    content: '{{ setupvar }}'
    dest: /tmp/facts/{{ ansible_hostname }}.yaml
    mode: 0600
  delegate_to: localhost

